<?php
// This file is auto-generated by setup/install.php
// Do NOT commit this file with real credentials.
// Run setup/install.php on your server to generate this file.

// If this file doesn't exist yet, run: /setup/install.php in your browser
if (!defined('DB_HOST')) {
    // Fallback: edit these values directly if not using the installer
    define('DB_HOST', 'localhost');
    define('DB_PORT', '3306');
    define('DB_NAME', '');      // Your MySQL database name
    define('DB_USER', '');      // Your MySQL username
    define('DB_PASS', '');      // Your MySQL password
    define('APP_URL',  'http://localhost');
}
