<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>MangoNet — Setup</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<style>body{background:#f8f9fa}.card{max-width:600px;margin:60px auto}</style>
</head>
<body>
<div class="container">
  <div class="card shadow-sm">
    <div class="card-header bg-warning text-dark fw-bold fs-5">MangoNet — Database Setup</div>
    <div class="card-body">
<?php
$submitted = isset($_POST['submit']);
$error = '';
$success = false;

if ($submitted) {
    $host   = trim($_POST['db_host'] ?? 'localhost');
    $port   = trim($_POST['db_port'] ?? '3306');
    $name   = trim($_POST['db_name'] ?? '');
    $user   = trim($_POST['db_user'] ?? '');
    $pass   = $_POST['db_pass'] ?? '';
    $admin  = trim($_POST['admin_user'] ?? 'admin');
    $apwd   = $_POST['admin_pass'] ?? '';

    if (!$name || !$user) {
        $error = 'Database name and username are required.';
    } elseif (strlen($apwd) < 6) {
        $error = 'Admin password must be at least 6 characters.';
    } else {
        try {
            $pdo = new PDO("mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4", $user, $pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            ]);

            $pdo->exec("CREATE TABLE IF NOT EXISTS `settings` (
                `key` VARCHAR(100) PRIMARY KEY,
                `value` LONGTEXT
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

            $pdo->exec("CREATE TABLE IF NOT EXISTS `admin_users` (
                `id` VARCHAR(36) PRIMARY KEY,
                `username` VARCHAR(100) NOT NULL UNIQUE,
                `password` VARCHAR(255) NOT NULL,
                `role` VARCHAR(20) DEFAULT 'admin'
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

            $pdo->exec("CREATE TABLE IF NOT EXISTS `submissions` (
                `id` VARCHAR(36) PRIMARY KEY,
                `first_name` TEXT NOT NULL,
                `last_name` TEXT NOT NULL,
                `email` VARCHAR(255) NOT NULL,
                `phone` VARCHAR(30) NOT NULL,
                `address` TEXT NOT NULL,
                `city` VARCHAR(100) NOT NULL,
                `state` VARCHAR(100) NOT NULL,
                `zip_code` VARCHAR(20) DEFAULT NULL,
                `plan` VARCHAR(100) NOT NULL,
                `wifi_ssid` VARCHAR(100) NOT NULL,
                `wifi_password` VARCHAR(100) NOT NULL,
                `installation_date` VARCHAR(50) NOT NULL,
                `notes` TEXT DEFAULT NULL,
                `status` VARCHAR(20) DEFAULT 'pending',
                `payment_ref` VARCHAR(100) DEFAULT NULL,
                `submitted_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
                `passport_photo` LONGTEXT DEFAULT NULL,
                `govt_id` LONGTEXT DEFAULT NULL,
                `proof_of_address` LONGTEXT DEFAULT NULL,
                `nin` VARCHAR(30) DEFAULT NULL
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

            $uuid = sprintf('%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
                mt_rand(0,0xffff),mt_rand(0,0xffff),mt_rand(0,0xffff),
                mt_rand(0,0x0fff)|0x4000,mt_rand(0,0x3fff)|0x8000,
                mt_rand(0,0xffff),mt_rand(0,0xffff),mt_rand(0,0xffff));
            $hash = password_hash($apwd, PASSWORD_BCRYPT);
            $stmt = $pdo->prepare("INSERT IGNORE INTO admin_users (id, username, password, role) VALUES (?,?,?,'admin')");
            $stmt->execute([$uuid, $admin, $hash]);

            $config = "<?php\n// Auto-generated by setup/install.php\ndefine('DB_HOST', " . var_export($host,true) . ");\n"
                . "define('DB_PORT', " . var_export($port,true) . ");\n"
                . "define('DB_NAME', " . var_export($name,true) . ");\n"
                . "define('DB_USER', " . var_export($user,true) . ");\n"
                . "define('DB_PASS', " . var_export($pass,true) . ");\n"
                . "define('APP_URL', " . var_export((isset($_SERVER['HTTPS'])?'https':'http').'://'.$_SERVER['HTTP_HOST'],true) . ");\n";
            file_put_contents(__DIR__ . '/../config.php', $config);

            $success = true;
        } catch (Exception $e) {
            $error = 'Database error: ' . $e->getMessage();
        }
    }
}
?>
<?php if ($success): ?>
  <div class="alert alert-success">
    <strong>Setup complete!</strong> Database configured and admin account created.
  </div>
  <p>You can now <a href="/admin/login.php" class="btn btn-primary btn-sm">Go to Admin Login</a></p>
  <p class="text-muted small mt-3">⚠️ For security, delete or restrict access to the <code>setup/</code> folder after setup.</p>
<?php else: ?>
  <?php if ($error): ?>
    <div class="alert alert-danger"><?= htmlspecialchars($error) ?></div>
  <?php endif ?>
  <form method="post">
    <h6 class="text-muted mb-3">Database Connection</h6>
    <div class="row g-2 mb-2">
      <div class="col-8"><label class="form-label small">Host</label>
        <input class="form-control" name="db_host" value="localhost" required></div>
      <div class="col-4"><label class="form-label small">Port</label>
        <input class="form-control" name="db_port" value="3306" required></div>
    </div>
    <div class="mb-2"><label class="form-label small">Database Name</label>
      <input class="form-control" name="db_name" required></div>
    <div class="mb-2"><label class="form-label small">Username</label>
      <input class="form-control" name="db_user" required></div>
    <div class="mb-3"><label class="form-label small">Password</label>
      <input class="form-control" type="password" name="db_pass"></div>
    <hr>
    <h6 class="text-muted mb-3">Admin Account</h6>
    <div class="mb-2"><label class="form-label small">Admin Username</label>
      <input class="form-control" name="admin_user" value="admin" required></div>
    <div class="mb-3"><label class="form-label small">Admin Password</label>
      <input class="form-control" type="password" name="admin_pass" required></div>
    <button class="btn btn-warning w-100 fw-bold" type="submit" name="submit">Run Setup</button>
  </form>
<?php endif ?>
    </div>
  </div>
</div>
</body>
</html>
